version: 2
jobs:
  shellcheck:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            sh android/build.sh

workflows:
  version: 2
  check-build:
    jobs:
      - shellcheck
