name: Remove build from mirror
on:
  workflow_dispatch:
    inputs:
      device: 
        description: Device to remove build for
      date:
        description: Date of build to remove
jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "${github.event.inputs.device}"
          echo "${github.event.inputs.date}"
