name: Remove build from mirror
on:
  workflow_dispatch:
    inputs:
      device: 
        description: Device to remove build for
      date:
        description: Date of build to remove
jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan mirror.lineageos.org >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.MIRROR_SSH }}"
      - name: Remove Build
        env:
          DEVICE: "${github.event.inputs.device}"
          DATE: "${github.event.inputs.date}"
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "ssh mirror@mirror.lineageos.org rmbuild $DEVICE $DATE"
